### ISSUE TITLE
Version sorting 

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#104] opened 2015-10-08 12:57 UTC
http://www.jsdelivr.com/projects/react
>React lastversion shows 0.14.0-rc1 instead of 0.14.0
https://github.com/jsdelivr/jsdelivr/issues/7281

The site uses the API sorting. We should short the versions correctly in the API by default. 0.14.0 > 0.14.0-rc1 > 0.14.0-beta1

**Comment by MartinKolarik** [comment] 2015-10-08 13:28
[Here's the code](https://github.com/jsdelivr/www.jsdelivr.com/blob/df5f6febb8ac59bad7d53bb788ee430c30cfb942/js/update/lib/version-compare.js) we were previously using.

**Comment by spicyj** [comment] 2015-10-08 15:28
I'd just use the semver package: https://www.npmjs.com/package/semver.

**Comment by MartinKolarik** [comment] 2015-10-08 15:32
The problem is that not all projects use semver and IIRC that package requires valid semver versions.

**Comment by tomByrer** [comment] 2015-10-10 17:54
> The problem is that not all projects use semver and IIRC that package requires valid semver versions

Plus sometimes a project will switch between valid & invalid semver.  Sometimes I feel like we should force our versions into valid semver to get around this.  I'm trying to think of real examples where the version is too strange; usually non-semver look like v1.003 or 20151016.

I think ` 0.14.0-rc1 > 0.14.0-beta1` will fail [compareStrings()](https://github.com/jsdelivr/www.jsdelivr.com/blob/df5f6febb8ac59bad7d53bb788ee430c30cfb942/js/update/lib/version-compare.js#L30-L42). 
Maybe pad odd versions with `.0` to make into good semver?

Related issue; if project changes from strange versions to semver, they won't track right (very vary rare, especially on github).

**Comment by tomByrer** [comment] 2015-10-10 18:17
I just remembered @megawac 's genius: https://github.com/megawac/SemVish.
& someone made a [CLI semverish](https://github.com/amoa/semverish)

**Comment by MartinKolarik** [comment] 2015-10-10 18:22
>I think 0.14.0-rc1 > 0.14.0-beta1 will fail compareStrings(). 

Nope, it works correctly.

**Comment by UnbounDev** [comment] 2015-10-11 17:25
This is ridiculously easy w/ [semver](https://www.npmjs.com/package/semver):

```js
versions = versions.sort(semver.rcompare);
```

Now fixed in v2:
![selection_022](https://cloud.githubusercontent.com/assets/7390369/10417935/15d2e416-7002-11e5-8fb3-22cea12b8daa.png)

**Comment by jimaek** [comment] 2015-10-11 17:36
@UnbounDev Can you apply the sorting to v1 as well? The website is using v1's listing of all libraries in a single request

**Comment by UnbounDev** [comment] 2015-10-11 17:37
:+1: Will do

**Comment by UnbounDev** [comment] 2015-10-11 17:45
@jimaek fixed in #105

**Closed** 2015-10-12 16:16 UTC
